# Generated by Django 5.2 on 2025-05-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("provider_services", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountmanager",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="company_name",
        ),
    ]
