# Generated by Django 5.2 on 2025-05-05 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("job", "Job Analysis"),
                            ("order", "Order Analysis"),
                            ("user", "User Activity Analysis"),
                            ("combined", "Combined Analysis"),
                        ],
                        default="combined",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quarter_from",
                    models.CharField(
                        choices=[
                            ("Q1", "Q1 (Jan-Mar)"),
                            ("Q2", "Q2 (Apr-Jun)"),
                            ("Q3", "Q3 (Jul-Sep)"),
                            ("Q4", "Q4 (Oct-Dec)"),
                        ],
                        max_length=2,
                    ),
                ),
                ("year_from", models.IntegerField()),
                (
                    "quarter_to",
                    models.CharField(
                        choices=[
                            ("Q1", "Q1 (Jan-Mar)"),
                            ("Q2", "Q2 (Apr-Jun)"),
                            ("Q3", "Q3 (Jul-Sep)"),
                            ("Q4", "Q4 (Oct-Dec)"),
                        ],
                        max_length=2,
                    ),
                ),
                ("year_to", models.IntegerField()),
                (
                    "pdf_report",
                    models.FileField(blank=True, null=True, upload_to="reports/pdf/"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderReportResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("orders_draft", models.IntegerField(default=0)),
                ("orders_submitted", models.IntegerField(default=0)),
                ("orders_in_progress", models.IntegerField(default=0)),
                ("orders_completed", models.IntegerField(default=0)),
                ("orders_cancelled", models.IntegerField(default=0)),
                (
                    "avg_processing_time",
                    models.FloatField(
                        blank=True,
                        help_text="Average time in days from order submission to completion",
                        null=True,
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_result",
                        to="stat_analysis.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Report Result",
                "verbose_name_plural": "Order Report Results",
            },
        ),
        migrations.CreateModel(
            name="JobReportResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_jobs", models.IntegerField(default=0)),
                (
                    "avg_completion_time_regular",
                    models.FloatField(
                        blank=True,
                        help_text="Average completion time in days for regular jobs",
                        null=True,
                    ),
                ),
                (
                    "avg_completion_time_wafer_run",
                    models.FloatField(
                        blank=True,
                        help_text="Average completion time in days for wafer run jobs",
                        null=True,
                    ),
                ),
                ("jobs_created", models.IntegerField(default=0)),
                ("jobs_active", models.IntegerField(default=0)),
                ("jobs_completed", models.IntegerField(default=0)),
                ("jobs_failed", models.IntegerField(default=0)),
                ("jobs_delayed", models.IntegerField(default=0)),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_result",
                        to="stat_analysis.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Report Result",
                "verbose_name_plural": "Job Report Results",
            },
        ),
        migrations.CreateModel(
            name="UserReportResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_active_users", models.IntegerField(default=0)),
                ("new_customers", models.IntegerField(default=0)),
                ("active_account_managers", models.IntegerField(default=0)),
                ("total_orders_by_top_manager", models.IntegerField(default=0)),
                (
                    "total_revenue_by_top_manager",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_result",
                        to="stat_analysis.report",
                    ),
                ),
                (
                    "top_customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="top_customer_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "top_performing_account_manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="top_performer_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Report Result",
                "verbose_name_plural": "User Report Results",
            },
        ),
    ]
