# Generated by Django 5.2 on 2025-05-05 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("provider_services", "0002_remove_accountmanager_bio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=10, unique=True)),
                ("job_name", models.CharField(max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("delayed", "Delayed"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[("regular", "Regular"), ("wafer_run", "Wafer Run")],
                        max_length=20,
                    ),
                ),
                ("starting_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "completion_time",
                    models.FloatField(
                        blank=True,
                        help_text="Time in days which were spent to complete the job.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="provider_services.serviceprovider",
                    ),
                ),
            ],
        ),
    ]
