# Generated by Django 5.2 on 2025-05-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="starting_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
